// "use client";
import Image from "next/image";
import Link from "next/link";
import Header from "@/components/Header";
import { Metadata } from "next/types";
import { Suspense } from "react";

// export const metadata: Metadata = {
//   title: "MyHome",
//   description: "Generated by create next app",
// };
async function getData() {
  const res = await fetch(
    "https://fl.sogamecdn.com/officialweb/homepage/data.json"
  );

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function Home() {
  const data = await getData();

  return (
    <>
      <Header></Header>
      <Suspense fallback={<p>Loading</p>}>
        {" "}
        <p>{JSON.stringify(data)}</p>
      </Suspense>
    </>
  );
}
